# btwiuse/arch:<image> docker image build dependencies.
# AUTO-GENERATED by gen-deps.sh from each ./<image>/Dockerfile -- do not edit.
# An edge `child: parent` comes from a FROM btwiuse/arch[:parent] line.
# Consumed by the Makefile to order builds; edges only, no recipes.

apk: main
bazel: main
bun: node
cairo: main
clojure: main
code-server: yay
curl3: yay
deno: node
dev: main
dkg: golang
dotnet: main
foundry: main
gear: rust
golang: main
grafana: main
jupyter: main
k0s: main
main:
mathematica-keygen: yay
mathematica-light: mathematica-keygen
mathematica: mathematica-keygen
nix: main
node-20: main
node-22: main
node-24: main
node: main
powershell: yay
prometheus: main
python: main
qemu: main
ruby: main
rust-goreleaser: rust
rust-nightly: rustup
rust: rustup
rustup: main
stylus: rust
swift: main
tea: main
texlive: main
tor: main
ufo: golang main
uupdump: main
v2ray: main
whois: main
windmill: main
wljs: wolframengine
wolframengine: mathematica-keygen
xmrig: main
xpra: yay
yay: main
zig: main
