# btwiuse/arch:<image> docker image build dependencies.
# AUTO-GENERATED by gen-deps.sh from each ./<image>/Dockerfile -- do not edit.
# An edge `child: parent` comes from a FROM btwiuse/arch[:parent] line.
# Consumed by the Makefile to order builds; edges only, no recipes.

apk: main
bazel: main
bun: node
cairo: main
clojure: main
code-server: main
codespace-btwiuse-arch-qrp54q6r29gx9: main
cosmwasm: rust
curl3: yay
deno: main
dev: main
dkg: golang
dotnet: main
elizaos-dev: dev
elizaos: bun
foundry: main
gear: rust
golang: main
grafana: main
ink: rust
jupyter: main
k0s: main
main:
mathematica-keygen: yay
mathematica-light: mathematica-keygen
mathematica: mathematica-keygen
near: rust
ninja: rust
nix: main
node-20: main
node-22: main
node-24: main
node: main
powershell: main
prometheus: main
python: main
qemu: main
ruby: main
rust-goreleaser: rust
rust-nightly: rustup
rust: rustup
rustup: main
solana: main rustup
stylus: rust
swift: main
tea: main
texlive: main
tor: main
ufo: golang main
uupdump: main
v2ray: main
vscode-base: bun node-22
vscode-dev: vscode-src
vscode-linux-x64-ci: vscode-src
vscode-linux-x64: vscode-src
vscode-reh-linux-x64-ci: vscode-src
vscode-reh-linux-x64: vscode-src
vscode-reh-web-linux-arm64-ci: vscode-src
vscode-reh-web-linux-arm64: vscode-src
vscode-reh-web-linux-x64-ci: vscode-src
vscode-reh-web-linux-x64-marketplace: vscode-src
vscode-reh-web-linux-x64-open-vsx: vscode-src
vscode-reh-web-linux-x64: vscode-src
vscode-src-codespace: vscode-base
vscode-src: vscode-base
vscode-web-ci: vscode-src
vscode-web-min: vscode-src
vscode-web-only: vscode-src
vscode-web: vscode-src
vscode: vscode-src
whois: main
windmill: main
wljs: wolframengine
wolframengine: mathematica-keygen
xmrig: main
yaourt: main
yay: main
zig: main
