#!/usr/bin/env bash
# Generate deps.mk from the FROM lines of every ./<image>/Dockerfile.
#
# An edge `child: parent` is emitted whenever ./<child>/Dockerfile contains
#   FROM btwiuse/arch:<parent>     (any stage, incl. builder stages), or
#   FROM btwiuse/arch              (untagged == :latest == the `main` image).
# Non-arch base images (goreleaser, cosmwasm, ...) are ignored.
set -euo pipefail
cd "$(dirname "$0")"

{
  echo "# btwiuse/arch:<image> docker image build dependencies."
  echo "# AUTO-GENERATED by gen-deps.sh from each ./<image>/Dockerfile -- do not edit."
  echo "# An edge \`child: parent\` comes from a FROM btwiuse/arch[:parent] line."
  echo "# Consumed by the Makefile to order builds; edges only, no recipes."
  echo

  for df in */Dockerfile; do
    img=${df%/Dockerfile}
    # Collect parent tags from all FROM lines.
    parents=$(grep -iE '^[[:space:]]*FROM[[:space:]]+btwiuse/arch' "$df" \
      | sed -E 's#^[[:space:]]*[Ff][Rr][Oo][Mm][[:space:]]+btwiuse/arch##' \
      | sed -E 's#^:([A-Za-z0-9._-]+).*#\1#; t; s#.*#main#' \
      | sort -u)
    # `main` is the root: depends on nothing.
    if [ "$img" = main ]; then parents=; fi
    # Drop self-references just in case.
    parents=$(printf '%s\n' $parents | grep -vx "$img" || true)
    echo "$img:${parents:+ }$(echo $parents | tr '\n' ' ')" | sed 's/ *$//'
  done
}
