#!/usr/bin/env bash
# Generate deps.mk from the FROM lines of every ./<image>/Dockerfile.
#
# An edge `child: parent` is emitted whenever ./<child>/Dockerfile contains
#   FROM btwiuse/arch:<parent>     (any stage, incl. builder stages), or
#   FROM btwiuse/arch              (untagged == :latest == the `main` image).
# Non-arch base images (goreleaser, cosmwasm, ...) are ignored.
set -euo pipefail
cd "$(dirname "$0")"

{
  echo "# btwiuse/arch:<image> docker image build dependencies."
  echo "# AUTO-GENERATED by gen-deps.sh from each ./<image>/Dockerfile -- do not edit."
  echo "# An edge \`child: parent\` comes from a FROM btwiuse/arch[:parent] line."
  echo "# Consumed by the Makefile to order builds; edges only, no recipes."
  echo

  for df in */Dockerfile; do
    img=${df%/Dockerfile}
    # Extract parent image from each `FROM btwiuse/arch[:<parent>]` line:
    #   FROM btwiuse/arch:rust AS x  -> rust
    #   FROM btwiuse/arch            -> main   (untagged == :latest)
    # awk is used instead of sed for portability (BSD/macOS vs GNU).
    parents=$(awk '
      tolower($1) == "from" && $2 ~ /^btwiuse\/arch(:|$)/ {
        n = index($2, ":")
        print (n ? substr($2, n + 1) : "main")
      }' "$df" | sort -u)
    # `main` is the root: depends on nothing.
    if [ "$img" = main ]; then parents=; fi
    # Drop self-references just in case.
    parents=$(printf '%s\n' $parents | grep -vx "$img" || true)
    echo "$img:${parents:+ }$(echo $parents | tr '\n' ' ')" | sed 's/ *$//'
  done
}
