FROM btwiuse/arch:rust

RUN cargo install --root /usr/local cargo-generate --features vendored-openssl
RUN cargo install --root /usr/local cargo-run-script
RUN cargo install --root /usr/local cosmwasm-check
